services:
  server:
    container_name: gw-exchanger
    restart: unless-stopped
    build:
      context: .
      target: final
    networks:
      - exchange
    env_file:
      - config.env
    ports:
      - 4000:443
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db

    image: postgres:17.5
    restart: always
    env_file:
      - config.env
    volumes:
      - ./internal/storages/postgres/database_setup:/docker-entrypoint-initdb.d
    networks:
      - exchange
    ports:
      - 5430:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "exchanger"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  exchanger-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  exchange:
      name: exchange
