services:
  server:
    container_name: gw-wallet
    build:
      context: .
      target: final
    environment:
      - POSTGRES_HOST=db_wallet
    env_file:
      - config.env
    ports:
      - 4001:4001
    networks:
      - exchange
    depends_on:
      db_wallet:
        condition: service_healthy
        restart: true

  db_wallet:
    container_name: db_wallet

    image: postgres:17.5
    restart: always
    env_file:
      - config.env
    volumes:
      - ./internal/storages/postgres/database_setup:/docker-entrypoint-initdb.d
    networks:
      - exchange
    ports:
      - 5431:5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "wallets"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
volumes:
  wallets-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  exchange:
      name: exchange