// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/latimeri-compute/go-exam-exchanger/gw-currency-wallet/internal/storages (interfaces: UserModelInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/users.go . UserModelInterface
//

// Package mock_storages is a generated GoMock package.
package mock_storages

import (
	reflect "reflect"

	storages "github.com/latimeri-compute/go-exam-exchanger/gw-currency-wallet/internal/storages"
	gomock "go.uber.org/mock/gomock"
)

// MockUserModelInterface is a mock of UserModelInterface interface.
type MockUserModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserModelInterfaceMockRecorder
	isgomock struct{}
}

// MockUserModelInterfaceMockRecorder is the mock recorder for MockUserModelInterface.
type MockUserModelInterfaceMockRecorder struct {
	mock *MockUserModelInterface
}

// NewMockUserModelInterface creates a new mock instance.
func NewMockUserModelInterface(ctrl *gomock.Controller) *MockUserModelInterface {
	mock := &MockUserModelInterface{ctrl: ctrl}
	mock.recorder = &MockUserModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserModelInterface) EXPECT() *MockUserModelInterfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserModelInterface) CreateUser(user *storages.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserModelInterfaceMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserModelInterface)(nil).CreateUser), user)
}

// FindUser mocks base method.
func (m *MockUserModelInterface) FindUser(user *storages.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindUser indicates an expected call of FindUser.
func (mr *MockUserModelInterfaceMockRecorder) FindUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUser", reflect.TypeOf((*MockUserModelInterface)(nil).FindUser), user)
}
